command:
  - "bash"
  - "start.sh"

env:
  - name: "NODE_ENV"
    value: "production"
  - name: "INSPIRE_DATABASE"
    value: "amr_ali._inspire"
  - name: "INSPIRE_AUTO_SETUP"
    value: "true"
  - name: "INSPIRE_WAREHOUSE_ID"
    value: "2023d0a3a188bd24"
  - name: "NOTEBOOK_PATH"
    value: "/Shared/inspire-ai/dbx_inspire_ai_agent"

resources:
  - name: "inspire-ai-sp"
    type: "service-principal"
